### ISSUE TITLE
Does not work if the port is not mapped directly

### ISSUE THREAD

**Issue by justinhj** [cstroe/java-jmx-in-docker-sample-app#1]
Thanks for this repo it's a great help. I have a problem where this only works if the container is run and the port is mapped directly (in your example 9010:9010)

If I map to a dynamic external port using -p 9010 and the dynamic port is usually something like 32772 then I can no longer connect using jconsole etc.

Any idea why this would be?

My guess is something to do with RMI protocol but I'm not sure.

**Comment by justinhj** [comment]
I see that this issue is mentioned here

https://forums.docker.com/t/exposing-mapped-jmx-ports-from-multiple-containers/5287/10


Seems the work around is to not use RMI

**Comment by justinhj** [comment]
Closing this since it's not related to your repo...

**Comment by cstroe** [comment]
I ran into the exact issue you mentioned while documenting this repo.  The ports have to match because RMI does its port negotiation at connection time.  From my experience (I didn't actually read the RMI code), it goes something like this if you use a randomly mapped external port:

```
Client: Open connection on port 32772, say hi.
JVM: hi, can we talk on port 9010? thanks.
Client: Open connection on port 9010 but gets no response since this port isn't mapped.
<hang>
```

So if you map the same port, the conversation goes something like this:

```
Client: Open connection on port 9010, say hi.
JVM: hi, can we talk on port 9010? thanks.
Client: Uhhmm, ya sure.  Open connection on port 9010.  Hi again!
JVM: Hello! So, I hear you want to chat about some JMX mbeans?
<connection successful>
```

It might be good to validate this understanding, but for now it works.

**Comment by justinhj** [comment]
Thanks for the update!

I hunted down a handful of links about this issue and I think we've found a
solution that switches the protocol from rmi to jmxmp. It works, but it's a
bit intrusive as you need to add a jar file with the jmxmp support to both
your tools and your application, as well as write code in the application
itself to start the JMX server with jmxmp

**Comment by cstroe** [comment]
JMXMP fits very well within a Docker environment.  Maybe it might be worth documenting it, even though there are some hoops to jump through...

**Comment by justinhj** [comment]
Will definitely put something together once everything is up and running.

**Comment by stokito** [comment]
I got the same problem. My container was configured to expose a port 9010 but since I have few containers on the same docker host so JMX port was published as another port 209010.
It looks like on handshake JMX returns an URL to which connect with and the url contains both external hostname and port.
So on starting of container we need to pass two env vars: one with external hostname and one with external port and inside container it should use the same port.
For example `entry.sh` or Tomcat's `setenv.sh` should contain lines like this:

```bash
if [ -z "$SERVICE_HOSTNAME" ]; then
    export SERVICE_HOSTNAME="0.0.0.0"
fi

export SERVICE_JMX_OPTS="-Dcom.sun.management.jmxremote.port=$SERVICE_JMX_PORT \
-Dcom.sun.management.jmxremote.rmi.port=$SERVICE_JMX_PORT \
-Djava.rmi.server.hostname=$SERVICE_HOSTNAME \
-Dcom.sun.management.jmxremote.local.only=false \
-Dcom.sun.management.jmxremote.password.file=${CATALINA_BASE}/conf/jmxremote.password \
-Dcom.sun.management.jmxremote.access.file=${CATALINA_BASE}/conf/jmxremote.access \
-Dcom.sun.management.jmxremote.ssl=false \
-Dsun.management.jmxremote.level=FINEST \
-Dsun.management.jmxremote.handlers=java.util.logging.ConsoleHandler \
-Djava.util.logging.ConsoleHandler.level=FINEST"
```

And to start container a command like:
```
SERVICE_JMX_PORT="209010"
exec docker run --name app-container --rm \
    -e SERVICE_SYSLOG=example.com \
    -e "SERVICE_JMX_PORT=${SERVICE_JMX_PORT}" \
    -p 8080:8080 -p ${SERVICE_JMX_PORT}:${SERVICE_JMX_PORT} \
    app-image
```

This is uncomfortable because you can't fix JMX port inside a container and need to pass two env vars.
Also JMXMP is not looking as a solution: its jar in maven looks strange, it looks outdated, VisualVM doesn't support it. Managing additional jar as dependency is something that I would like to avoid.

**Comment by justinhj** [comment]
I've been using JMXMP for a few months without any trouble. Sure it's not
ideal that I had to hunt for a jar file from a secure source but we have a
few other things that need a folder of jar files in deployment so it wasn't
a big deal.
